bims/urls.py
# coding=utf-8

from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from rest_framework.documentation import include_docs_urls
from bims.views.map import MapPageView
from bims.views.landing_page import LandingPageView
from bims.api_views.location_site import (
    LocationSiteList,
    LocationSiteDetail,
    LocationSiteClusterList
)
from bims.api_views.location_type import (
    LocationTypeAllowedGeometryDetail
)
from bims.api_views.non_biodiversity_layer import (
    NonBiodiversityLayerList
)
from bims.api_views.taxon import TaxonDetail
from bims.api_views.cluster import ClusterList
from bims.api_views.collection import (
    GetCollectionExtent,
    CollectionDownloader,
    ClusterCollection
)
from bims.api_views.collector import CollectorList
from bims.api_views.category_filter import CategoryList
from bims.api_views.search import SearchObjects
from bims.api_views.validate_object import ValidateObject
from bims.api_views.get_biorecord import GetBioRecords
from bims.views.links import LinksCategoryView
from bims.views.activate_user import activate_user
from bims.views.csv_upload import CsvUploadView
from bims.views.shapefile_upload import ShapefileUploadView, process_shapefiles
from bims.views.under_development import UnderDevelopmentView
from bims.views.non_validated_list import NonValidatedObjectsView
from bims.views.non_validated_user_list import NonValidatedObjectsUserView
from bims.views.bio_records_edit import BioRecordsUpdateView
from bims.views.collection_upload import CollectionUploadView
from bims.api_views.send_notification_to_validator import \
    SendNotificationValidation
from bims.views.locate import filter_farm_ids_view, get_farm_view

api_urls = [
    url(r'^api/location-type/(?P<pk>[0-9]+)/allowed-geometry/$',
        LocationTypeAllowedGeometryDetail.as_view()),
    url(r'^api/location-site/cluster/$', LocationSiteClusterList.as_view()),
    url(r'^api/location-site/$', LocationSiteList.as_view()),
    url(r'^api/location-site/(?P<pk>[0-9]+)/$',
        LocationSiteDetail.as_view(),
        name='location-site-detail'),
    url(r'^api/taxon/(?P<pk>[0-9]+)/$',
        TaxonDetail.as_view()),
    url(r'^api/cluster/(?P<administrative_level>\w+)/$',
        ClusterList.as_view()),
    url(r'^api/collection/extent/$',
        GetCollectionExtent.as_view()),
    url(r'^api/collection/cluster/$',
        ClusterCollection.as_view()),
    url(r'^api/collection/download/$',
        CollectionDownloader.as_view()),
    url(r'^collection/check_process/$',
        CollectionDownloader.as_view()),
    url(r'^api/search/$',
        SearchObjects.as_view(), name='search-api'),
    url(r'^api/list-collector/$',
        CollectorList.as_view(), name='list-collector'),
    url(r'^api/list-category/$',
        CategoryList.as_view(), name='list-date-category'),
    url(r'^api/list-non-biodiversity/$',
        NonBiodiversityLayerList.as_view(),
        name='list-non-biodiversity-layer'),
    url(r'^api/validate-object/$',
        ValidateObject.as_view(), name='validate-object'),
    url(r'^api/get-bio-object/$',
        GetBioRecords.as_view(), name='get-bio-object'),
    url(r'^api/send-email-validation/$',
        SendNotificationValidation.as_view(), name='send-email-validation'),
    url(r'^api/filter-farm-id/$',
        filter_farm_ids_view, name='filter-farm-id'),
    url(r'^api/get-farm/(?P<farm_id>[\w-]+)/$',
        get_farm_view, name='get-farm'),
]


urlpatterns = [
    url(r'^$', LandingPageView.as_view(), name='landing-page'),
    url(r'^map/$', MapPageView.as_view()),
    url(r'^profile/$',
        login_required(lambda request: RedirectView.as_view(
            url=reverse_lazy('profile_detail', kwargs={
                'username': request.user.username
            }), permanent=False)(request)), name='user-profile'),
    url(r'^upload/$', CsvUploadView.as_view(),
        name='csv-upload'),
    url(r'^upload_shp/$', ShapefileUploadView.as_view(),
        name='shapefile-upload'),
    url(r'^process_shapefiles/$', process_shapefiles,
        name='process_shapefiles'),
    url(r'^links/$', LinksCategoryView.as_view(), name = 'link_list'),
    url(r'^api/docs/', include_docs_urls(title='BIMS API')),
    url(r'^activate-user/(?P<username>[\w-]+)/$',
        activate_user, name='activate-user'),
    url(r'^under-development/$',
        UnderDevelopmentView.as_view(), name='under-development'),
    url(r'^nonvalidated-list/$',
        NonValidatedObjectsView.as_view(), name='nonvalidated-list'),
    url(r'^nonvalidated-user-list/$',
        NonValidatedObjectsUserView.as_view(), name='nonvalidated-user-list'),
    url(r'^update/(?P<pk>\d+)/$',
        BioRecordsUpdateView.as_view(), name='update-records'),
    url(r'^upload_collection/$', CollectionUploadView.as_view(),
        name='upload-collection'),
] + api_urls

core/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from geonode.urls import urlpatterns as geonode_urlpatterns


# GeoNode has to be in root url conf.
# It cannot be included in include() function because it contains i18n urls
urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^contact/', include('contactus.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^', include('bims.urls')),
    url(r'^bibliography/',
        include(('td_biblio.urls', 'bibliography'),
                namespace = 'td_biblio')),
    url(r'^', include('example.urls')),

    # prometheus monitoring
    url(r'', include('django_prometheus.urls')),

    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^geonode/?$',
        TemplateView.as_view(template_name='site_index.html'),
        name='home'),
]

urlpatterns += geonode_urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

td_biblio/urls.py
from django.conf.urls import url
from td_biblio.views.bibliography import (
    EntryListView,
    EntryBatchImportView,
)

urlpatterns = [
    url('^$', EntryListView.as_view(), name='entry_list'),
    url('^import/$', EntryBatchImportView.as_view(), name='import'),
]

bims/models/biological_collection_record.py
# coding=utf-8
"""Biological collection record model definition.

"""

from django.conf import settings
from django.db import models
from django.dispatch import receiver
from django.utils import timezone

from bims.models.location_site import LocationSite
from bims.models.taxon import Taxon
from bims.utils.cluster import (
    update_cluster_by_collection,
    update_cluster_by_site
)
from bims.utils.gbif import update_collection_record


class BiologicalCollectionRecord(models.Model):
    """Biological collection model."""
    CATEGORY_CHOICES = (
        ('alien', 'Alien'),
        ('indigenous', 'Indigenous'),
        ('translocated', 'Translocated')
    )
    site = models.ForeignKey(
        LocationSite,
        models.CASCADE,
        related_name='biological_collection_record',
    )
    original_species_name = models.CharField(
        max_length=100,
        blank=True,
        default='',
    )
    category = models.CharField(
        max_length=50,
        choices=CATEGORY_CHOICES,
        blank=True,
    )
    present = models.BooleanField(
        default=True,
    )
    absent = models.BooleanField(
        default=True,
    )
    collection_date = models.DateField(
        default=timezone.now
    )
    collector = models.CharField(
        max_length=100,
        blank=True,
        default='',
        verbose_name='collector or observer',
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    notes = models.TextField(
        blank=True,
        default='',
    )
    taxon_gbif_id = models.ForeignKey(
        Taxon,
        models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Taxon GBIF ',
    )
    validated = models.BooleanField(
        default=False,
    )
    ready_for_validation = models.BooleanField(
        default=False,
    )

    # noinspection PyClassicStyleClass
    class Meta:
        """Meta class for project."""
        app_label = 'bims'
        permissions = (
            ('can_upload_csv', 'Can upload CSV'),
            ('can_upload_shapefile', 'Can upload Shapefile'),
            ('can_validate_data', 'Can validate data'),
        )

    def on_post_save(self):
        if not self.taxon_gbif_id:
            update_collection_record(self)

    def get_children(self):
        rel_objs = [f for f in self._meta.get_fields(include_parents=False)
                    if (f.one_to_many or f.one_to_one) and
                    f.auto_created and not f.concrete]

        for rel_obj in rel_objs:
            try:
                return getattr(self, rel_obj.get_accessor_name())
            except AttributeError:
                continue

    @staticmethod
    def get_children_model():
        rel_objs = [f for f in BiologicalCollectionRecord._meta.get_fields(
            include_parents=False)
                    if (f.one_to_many or f.one_to_one) and
                    f.auto_created and not f.concrete]
        related_models = []
        for rel_obj in rel_objs:
            related_models.append(rel_obj.related_model)
        return related_models

    def __init__(self, *args, **kwargs):
        super(BiologicalCollectionRecord, self).__init__(*args, **kwargs)
        self.__original_validated = self.validated

    def is_cluster_generation_applied(self):
        if self.__original_validated != self.validated:
            return True
        if self.validated:
            return True
        return False


@receiver(models.signals.post_save)
def collection_post_save_handler(sender, instance, **kwargs):
    """
    Fetch taxon from original species name.
    """
    if not issubclass(sender, BiologicalCollectionRecord):
        return
    models.signals.post_save.disconnect(
        collection_post_save_handler,
    )
    instance.on_post_save()
    if instance.is_cluster_generation_applied():
        update_cluster_by_collection(instance)
    models.signals.post_save.connect(
        collection_post_save_handler,
    )


@receiver(models.signals.post_save)
def collection_post_save_update_cluster(sender, instance, **kwargs):
    if not issubclass(sender, BiologicalCollectionRecord):
        return


@receiver(models.signals.post_delete)
def cluster_post_delete_handler(sender, instance, using, **kwargs):
    if not issubclass(sender, BiologicalCollectionRecord) and \
            not issubclass(sender, LocationSite):
        return
    if issubclass(sender, BiologicalCollectionRecord):
        if instance.is_cluster_generation_applied():
            update_cluster_by_collection(instance)
    if issubclass(sender, LocationSite):
        update_cluster_by_site(instance)

bims/models/boundary.py
# coding=utf-8
"""Boundary model definition.
"""

import json
from django.contrib.gis.db import models
from bims.models.boundary_type import BoundaryType


class Boundary(models.Model):
    """Boundary model."""

    name = models.CharField(
        max_length=128,
        blank=False,
    )
    code_name = models.CharField(
        max_length=128,
        default="EMPTY"
    )
    type = models.ForeignKey(
        BoundaryType, on_delete=models.CASCADE
    )
    geometry = models.MultiPolygonField(blank=True, null=True)
    centroid = models.PointField(
        null=True,
        blank=True,
    )
    top_level_boundary = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return u'%s - %s' % (
            self.type, self.name)

    class Meta:
        unique_together = ("name", "code_name", "type")

    def generate_cluster(self):
        """ Generate cluster for the boundary.
        This will generate by the rule.
        If the boundary is lowest, it will generate from
        counting record.
        If boundary is not lowest, it will generate from
        calculating cluster of lower boundary
        """
        from bims.models.boundary_type import BoundaryType
        from bims.models.cluster import Cluster
        from bims.utils.cluster import update_cluster

        # get clusters below of this boundary
        clusters = Cluster.objects.filter(
            boundary__top_level_boundary=self).order_by(
            'module'
        )
        # if lowest boundary, do actual update cluster
        if self.type == BoundaryType.lowest_type():
            update_cluster(self)
        else:
            # if not lowest, calculate from it's cluster boundary
            Cluster.objects.filter(
                boundary=self).delete()
            for cluster in clusters:
                # create/update new cluster count
                try:
                    self_cluster = Cluster.objects.get(
                        boundary=self,
                        module=cluster.module
                    )
                except Cluster.DoesNotExist:
                    self_cluster = Cluster.objects.create(
                        boundary=self,
                        module=cluster.module
                    )

                # add site count
                self_cluster.site_count = (
                    self_cluster.site_count + cluster.site_count
                )

                # update detail
                details = {
                    'records': 0,
                    'sites': 0,
                    'survey': 0
                }
                try:
                    details = json.loads(
                        self_cluster.details)
                except ValueError:
                    pass

                # adding value from lower cluster
                try:
                    cluster_detail = json.loads(cluster.details)
                    details['records'] += cluster_detail['records']
                    details['sites'] += cluster_detail['sites']
                    details['survey'] += cluster_detail['survey']
                except ValueError:
                    pass
                self_cluster.details = json.dumps(details)
                self_cluster.save()

bims/models/boundary_type.py
# coding=utf-8
"""Boundary model definition.
"""

from django.contrib.gis.db import models
from django.db.models import Max


class BoundaryType(models.Model):
    """Boundary type model."""

    name = models.CharField(
        max_length=128,
        blank=False,
        unique=True
    )

    level = models.IntegerField(
        null=True,
        blank=True,
        help_text='what level of this boundary type'
    )

    def __str__(self):
        return u'%s' % self.name

    @staticmethod
    def lowest_type():
        lowest_level = BoundaryType.objects.all().aggregate(max=Max('level'))
        return BoundaryType.objects.get(
            level=lowest_level['max']
        )

bims/models/carousel_header.py
# coding=utf-8
"""Carousel header model definition.

"""

from django.db import models
from ordered_model.models import OrderedModel


class CarouselHeader(OrderedModel):
    """Carousel header model."""

    banner = models.ImageField(
        upload_to='banner'
    )

    description = models.TextField(
        blank=True,
        default='',
    )

bims/forms/bio_records_update.py
# coding=utf-8
from django.contrib.gis import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    Fieldset,
    Field,
)
from bims.models import BiologicalCollectionRecord


class BioRecordsForm(forms.ModelForm):
    class Meta:
        model = BiologicalCollectionRecord
        fields = (
            'site',
            'original_species_name',
            'category',
            'present',
            'absent',
            'collection_date',
            'notes',
            'taxon_gbif_id'
        )

    def __init__(self, *args, **kwargs):
        form_title = ''
        self.helper = FormHelper()
        layout = Layout(
            Fieldset(
                form_title,
                Field('original_species_name', css_class='form-control'),
                Field('category', css_class='form-control'),
                Field('present', css_class='form-control'),
                Field('absent', css_class='form-control'),
                Field('collection_date', css_class='form-control'),
                Field('notes', css_class='form-control'),
                Field('taxon_gbif_id', css_class='form-control'),
                Field('site', css_class='form-control'),
            )
        )
        self.helper.layout = layout
        self.helper.html5_required = False
        self.helper.form_tag = False
        super(BioRecordsForm, self).__init__(*args, **kwargs)

bims/forms/csv_upload.py
# coding=utf-8
"""Forms to upload csv.
"""

from django import forms
from bims.models.csv_document import CSVDocument


class CsvUploadForm(forms.ModelForm):
    """Csv upload form"""
    class Meta:
        model = CSVDocument
        fields = '__all__'

bims/forms/shapefile_upload.py
# coding=utf-8
"""Forms to upload shapefile.
"""

from django import forms
from bims.models.shapefile import Shapefile


class ShapefileUploadForm(forms.ModelForm):
    """Shapefile upload form"""

    token = ''

    class Meta:
        model = Shapefile
        fields = ('shapefile', 'token')

    def save(self, commit=True):
        self.instance.token = self.token
        return super(ShapefileUploadForm, self).save(commit=commit)

bims/templates/td_biblio/entry_import.html
{% extends "td_biblio/layouts/one_col.html" %}
{% load static from staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Import publications" %}{% endblock page_title %}

{% block page_class %}bibliography import{% endblock page_class %}

{% block main_content %}

{% block content %}
    <style>
        .button, button,
        input[type="button"],
        input[type="reset"],
        input[type="submit"] {
                background-color: #526B43 !important;
                border: 0.1rem solid #526B43 !important;
            }


    </style>
    <link href="{% static "css/navbar.css" %}" rel="stylesheet">

    <h2>{% trans "Import new publications" %}</h2>
<form
  class="batch-import-form"
  action="{% url 'td_biblio:import' %}"
  method="post"
>
  {% csrf_token %}

  {{ form }}

  <div class="form-actions">
    <input
      type="reset"
      name="{% trans "Cancel" %}"
      value="{% trans "cancel" %}"
      class="cancel">
    <input
      type="submit"
      name="{% trans "Import" %}"
      value="{% trans "submit" %}"
      class="submit"
    style="color: white;">
  </div>
</form>

{% endblock content %}
{% endblock main_content %}

bims/templates/td_biblio/entry_item.html
{% include "td_biblio/bibliography_styles/ieeetr.html" %}

bims/templates/td_biblio/entry_list.html
{% extends "td_biblio/layouts/two_cols_left_sidebar.html" %}
{% load static from staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Publications" %}{% endblock page_title %}

{% block page_class %}page biblio{% endblock page_class %}

{% block left_sidebar_extras %}

<h3>{% trans "Metrics" %}</h3>

<div id="publications-stats">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <!-- CSS Reset -->
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <!-- Milligram CSS minified -->
    <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    <!-- Override styles -->
    <link href="{% static "css/navbar.css" %}" rel="stylesheet">
    <style>
             body {
                   margin-top: 8%;
             }
        </style>
    <table>
        <tr class="metric">
            <td>{% trans "Publications" %}</td>
            <td><span class="counter">{{ n_publications_filter }}</span></td>
            <td>{{ n_publications_total }}</td>
        </tr>
        <tr class="metric">
            <td>{% trans "Authors" %}</td>
            <td><span class="counter">{{ n_authors_filter }}</span></td>
            <td>{{ n_authors_total }}</td>
        </tr>
        <tr class="metric">
            <td>{% trans "Journals" %}</td>
            <td><span class="counter">{{ n_journals_filter }}</span></td>
            <td>{{ n_journals_total }}</td>
        </tr>
    </table>

    <div class="legend">
        <span class="counter">XX</span> {% trans "after filtering" %}
    </div>
</div>

<h3>{% trans "Filters" %}</h3>

<form method="get" action="" id="publication-list-filters" class="custom">

    <label for="filter-year">{% trans "Year" %}</label>
    <select name="year" id="filter-year">
        <option value="">
            {% trans "All" %}
        </option>
        {% for publication_year in publication_years %}
        <option value="{{ publication_year.year }}" {% if publication_year.year == current_publication_year.year %}selected="selected"{% endif %}>
            {{ publication_year.year }}
        </option>
        {% endfor %}
    </select>

    <label for="filter-author">{% trans "Author" %}</label>
    <select name="author" id="filter-author">
        <option value="">
            {% trans "All" %}
        </option>
        {% for author in publication_authors %}
        <option value="{{ author.id }}" {% if author.id == current_publication_author %}selected="selected"{% endif %}>
            {{ author.get_formatted_name }}
        </option>
        {% endfor %}
    </select>

    <label for="filter-collection">{% trans "Collection" %}</label>
    <select name="collection" id="filter-collection">
        <option value="">
            {% trans "All" %}
        </option>
        {% for collection in publication_collections %}
        <option value="{{ collection.id }}" {% if collection.id == current_publication_collection %}selected="selected"{% endif %}>
            {{ collection.name }}
        </option>
        {% endfor %}
    </select>
</form>
{% endblock left_sidebar_extras %}

{% block main_content %}

        <h2>{% trans "Publications" %}</h2>

        {% if request.user.is_superuser %}
        <div class="import-message">
          <a href="{% url 'td_biblio:import' %}" class="button import"
                  data-toggle="Import with DOIs or PubMed ids">
              Import with DOIs or PubMed ids
          </a>
        </div>
        {% endif %}

        {% include "td_biblio/partials/publication_list_by_year.html" with publications=entry_list %}

        {% if is_paginated %}
        <div class="pagination-centered">

            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}" class="pagination">&laquo;</a></li>
                {% endif %}
                <li class="current">
                    <a href="">{{ page_obj.number }}</a>
                    {{ page_obj.start_index }} - {{ page_obj.end_index }}</li>
                {% if page_obj.has_next %}
                <li class="arrow"><a href="?page={{ page_obj.next_page_number }}" class="pagination">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
{% endblock main_content %}